; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
lib_deps =
    https://github.com/bblanchon/ArduinoJson@7.4.2
    https://github.com/shah253kt/Logger@1.0.2
    https://github.com/256dpi/arduino-mqtt@2.5.2
    https://github.com/adafruit/Adafruit_NeoPixel@1.15.2


[esp32-c3]
board = esp32-c3-devkitm-1
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.partitions = partition.csv
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder


[env:esp32-c3-devkitm-1]
extends = base, esp32-c3
extra_scripts = post:./merge-bin.py


[env:esp32-c3-devkitm-1_debug]
extends = base, esp32-c3
build_type = debug

[env]
extra_scripts = merge-bin.py