; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/tzapu/WiFiManager
    https://github.com/bblanchon/ArduinoJson
    https://github.com/Zanduino/INA
    shah253kt/Logger
    https://github.com/256dpi/arduino-mqtt

[base]
board = esp32dev
build_flags =
    ${env.build_flags}
    -Wall
monitor_filters =
    default
    esp32_exception_decoder
board_build.partitions = partition.csv

[env:esp32-c3-devkitm-1]
extends = base
board = esp32-c3-devkitm-1

[env:esp32-c3-devkitm-1-dev]
extends = base
board = esp32-c3-devkitm-1
build_type = debug
